### ISSUE TITLE
OpenNebula Ansible dynamic inventory script

### ISSUE THREAD

**Issue by marcindulak** [OpenNebula/addon-pyone#10]
The latest script is available in the https://github.com/marcindulak/ansible/tree/one-dynamic-inventory branch. Download `contrib/inventory/opennebula.py` and `contrib/inventory/opennebula.ini`. The example usage is described inside of the script.

The place for it is in https://github.com/ansible/ansible/tree/devel/contrib but I would like to get some feedback first. Are you planning to maintain an ansible branch for the purpose of OpenNebula as mentioned at https://forum.opennebula.org/t/new-addon-pyone/?

I would like the feedback about the following:

1. I've noticed something unexpected about `one.vmpool.info` API call. Compare it's output with CLI `onevm show 0` I see that some information available from CLI is not present in API.
For example `HOST`, `CLUSTER ID`, `CLUSTER` are not returned by the API call.

```
from pyone.util import one2dict
import pyone
pyone.OneServer("http://one/RPC2", session="oneadmin:onepass" )
vmpool = one.vmpool.info(-2, -1, -1, -1)
print(one2dict(vmpool)['VM_POOL']['VM'][0])
```

```
[oneadmin@frontend ~]$ onevm show 0
VIRTUAL MACHINE 0 INFORMATION                                                   
ID                  : 0                   
NAME                : testvm-0            
USER                : oneadmin            
GROUP               : oneadmin            
STATE               : ACTIVE              
LCM_STATE           : RUNNING             
RESCHED             : No                  
HOST                : node1               
CLUSTER ID          : 0                   
CLUSTER             : default             
START TIME          : 03/09 22:17:15      
END TIME            : -                   
DEPLOY ID           : one-0 
...              
```

2. Is the opennebula.py inventory script useful in what it does? My idea was to provide ansible inventory groups based on `CLUSTER` and `LABELS`.

**Comment by rvalle** [comment]
I think it is a dynamic inventory is a great idea. Users can create their inventory by simply using the Sunstone web instead of editing yaml files. 

With regards to the differences from the CLI interface I think you are comparing two different calls.

```vmpool``` provides you with the list of vms, but I think then you have to iterate and retrieve the information of each.

there is another call that is ```one.vm.info(ID)```, i think. That should be the equivalent to ```onevm show ID```

Can you have a look and see if you get it to work?

With regards to the Ansible branch, yes, I am planing on publishing something hopefully this weekend. Perhaps one or two api calls working, and with the community we can go completing them.

I guess we can now add also the dynamic inventory you are creating. Do you know how are  these type of components distributed?

**Comment by marcindulak** [comment]
I've tried also `one.vm.info(ID)` and got basically the same output:
```
vmpool = one.vmpool.info(-2, -1, -1, -1)
print(one2dict(vmpool)['VM_POOL']['VM'][0])
show = one.vm.info(0)
print(one2dict(show))
```

For the dynamic inventory we just need to create a pull request to include it under https://github.com/ansible/ansible/tree/devel/contrib. I don't think there are any tests for the inventory scripts. There are lots of pull request in ansible, we will need to attract an attention of an ansible developer like in this case https://groups.google.com/forum/#!topic/ansible-devel/baZVh5TeI1c

**Comment by rvalle** [comment]
I can get some of the information you are after in my environment:
```
        vm = one.vm.info(0)
        template = one2dict(vm.TEMPLATE)
        utemplate = one2dict(vm.USER_TEMPLATE)
        labels = utemplate['USER_TEMPLATE']['LABELS']
        culsterId = template['TEMPLATE']['DISK']['CLUSTER_ID']
```

If you need to debug what you got back you can always use the ```toxml()``` method, note you only need to use ```one2dict``` for the elements that are marked as ```anyType``` in the XSD. Otherwise the object has members for accessing them, like with vm.ID, etc.

I notice in the returned XML that the ```HOST``` can be found on the HISTORY records, which makes sense, because the VMs may be rescheduled, etc:

```
vm.toxml()

<?xml version="1.0"?>
<VM xmlns="http://opennebula.org/XMLSchema">
    <ID>0</ID>
    <UID>0</UID>
    <GID>0</GID>
    <UNAME>oneadmin</UNAME>
    <GNAME>oneadmin</GNAME>
    <NAME>Debian 9 - KVM-0</NAME>
    <PERMISSIONS>
        <OWNER_U>1</OWNER_U>
        <OWNER_M>1</OWNER_M>
        <OWNER_A>0</OWNER_A>
        <GROUP_U>0</GROUP_U>
        <GROUP_M>0</GROUP_M>
        <GROUP_A>0</GROUP_A>
        <OTHER_U>0</OTHER_U>
        <OTHER_M>0</OTHER_M>
        <OTHER_A>0</OTHER_A>
    </PERMISSIONS>
    <LAST_POLL>1520700583</LAST_POLL>
    <STATE>3</STATE>
    <LCM_STATE>3</LCM_STATE>
    <PREV_STATE>3</PREV_STATE>
    <PREV_LCM_STATE>3</PREV_LCM_STATE>
    <RESCHED>0</RESCHED>
    <STIME>1519563489</STIME>
    <ETIME>0</ETIME>
    <DEPLOY_ID>one-0</DEPLOY_ID>
    <MONITORING>
        <CPU>2.94</CPU>
        <DISKRDBYTES>76499228</DISKRDBYTES>
        <DISKRDIOPS>4362</DISKRDIOPS>
        <DISKWRBYTES>4354048</DISKWRBYTES>
        <DISKWRIOPS>277</DISKWRIOPS>
        <DISK_SIZE>
            <ID>0</ID>
            <SIZE>337</SIZE>
        </DISK_SIZE>
        <DISK_SIZE>
            <ID>1</ID>
            <SIZE>1</SIZE>
        </DISK_SIZE>
        <MEMORY>307200</MEMORY>
        <STATE>a</STATE>
    </MONITORING>
    <TEMPLATE>
        <AUTOMATIC_DS_REQUIREMENTS>"CLUSTERS/ID" @&gt; 0</AUTOMATIC_DS_REQUIREMENTS>
        <AUTOMATIC_REQUIREMENTS>(CLUSTER_ID = 0) &amp; !(PUBLIC_CLOUD = YES)</AUTOMATIC_REQUIREMENTS>
        <CONTEXT>
            <DISK_ID>1</DISK_ID>
            <NETWORK>YES</NETWORK>
            <SSH_PUBLIC_KEY />
            <TARGET>hda</TARGET>
        </CONTEXT>
        <CPU>1</CPU>
        <DISK>
            <ALLOW_ORPHANS>NO</ALLOW_ORPHANS>
            <CLONE>YES</CLONE>
            <CLONE_TARGET>SYSTEM</CLONE_TARGET>
            <CLUSTER_ID>0</CLUSTER_ID>
            <DATASTORE>default</DATASTORE>
            <DATASTORE_ID>1</DATASTORE_ID>
            <DEV_PREFIX>vd</DEV_PREFIX>
            <DISK_ID>0</DISK_ID>
            <DISK_SNAPSHOT_TOTAL_SIZE>0</DISK_SNAPSHOT_TOTAL_SIZE>
            <DISK_TYPE>FILE</DISK_TYPE>
            <DRIVER>qcow2</DRIVER>
            <IMAGE>Debian 9 - KVM</IMAGE>
            <IMAGE_ID>0</IMAGE_ID>
            <IMAGE_STATE>2</IMAGE_STATE>
            <LN_TARGET>SYSTEM</LN_TARGET>
            <ORIGINAL_SIZE>2048</ORIGINAL_SIZE>
            <READONLY>NO</READONLY>
            <SAVE>NO</SAVE>
            <SIZE>2048</SIZE>
            <SOURCE>/var/lib/one//datastores/1/e113485d81279f7c310b7a0f092afe7f</SOURCE>
            <TARGET>vda</TARGET>
            <TM_MAD>ssh</TM_MAD>
            <TYPE>FILE</TYPE>
        </DISK>
        <GRAPHICS>
            <LISTEN>0.0.0.0</LISTEN>
            <PORT>5900</PORT>
            <TYPE>vnc</TYPE>
        </GRAPHICS>
        <MEMORY>300</MEMORY>
        <OS>
            <ARCH>x86_64</ARCH>
        </OS>
        <TEMPLATE_ID>0</TEMPLATE_ID>
        <VMID>0</VMID>
    </TEMPLATE>
    <USER_TEMPLATE>
        <LABELS>TEST,DEV</LABELS>
        <LOGO>images/logos/debian.png</LOGO>
    </USER_TEMPLATE>
    <HISTORY_RECORDS>
        <HISTORY>
            <OID>0</OID>
            <SEQ>0</SEQ>
            <HOSTNAME>hv2</HOSTNAME>
            <HID>1</HID>
            <CID>0</CID>
            <STIME>1519563500</STIME>
            <ETIME>1519625422</ETIME>
            <VM_MAD>kvm</VM_MAD>
            <TM_MAD>ssh</TM_MAD>
            <DS_ID>0</DS_ID>
            <PSTIME>1519563500</PSTIME>
            <PETIME>1519563517</PETIME>
            <RSTIME>1519563517</RSTIME>
            <RETIME>1519625422</RETIME>
            <ESTIME>0</ESTIME>
            <EETIME>0</EETIME>
            <ACTION>44</ACTION>
            <UID>-1</UID>
            <GID>-1</GID>
            <REQUEST_ID>-1</REQUEST_ID>
        </HISTORY>
        <HISTORY>
            <OID>0</OID>
            <SEQ>1</SEQ>
            <HOSTNAME>hv2</HOSTNAME>
            <HID>1</HID>
            <CID>0</CID>
            <STIME>1520700053</STIME>
            <ETIME>0</ETIME>
            <VM_MAD>kvm</VM_MAD>
            <TM_MAD>ssh</TM_MAD>
            <DS_ID>0</DS_ID>
            <PSTIME>0</PSTIME>
            <PETIME>0</PETIME>
            <RSTIME>1520700053</RSTIME>
            <RETIME>0</RETIME>
            <ESTIME>0</ESTIME>
            <EETIME>0</EETIME>
            <ACTION>0</ACTION>
            <UID>-1</UID>
            <GID>-1</GID>
            <REQUEST_ID>-1</REQUEST_ID>
        </HISTORY>
    </HISTORY_RECORDS>
</VM>
```

**Comment by marcindulak** [comment]
This is also what I see.
The API presents `CLUSTER_ID` as a property of `NIC` and `DISK`, and not as a property of the VM itself, but CLI output suggests `CLUSTER_ID` is a property of VM
https://docs.opennebula.org/5.4/operation/host_cluster_management/cluster_guide.html
I wonder whether it is possible to have a VM that has `NIC` in one `CLUSTER_ID` and `DISK` in another `CLUSTER_ID`.

```
...
  <TEMPLATE>
    <AUTOMATIC_DS_REQUIREMENTS>"CLUSTERS/ID" @&gt; 0</AUTOMATIC_DS_REQUIREMENTS>
    <AUTOMATIC_REQUIREMENTS>(CLUSTER_ID = 0) &amp; !(PUBLIC_CLOUD = YES)</AUTOMATIC_REQUIREMENTS>
    <CONTEXT>
...
    </CONTEXT>
    <CPU>1</CPU>
    <DISK>
      <ALLOW_ORPHANS>NO</ALLOW_ORPHANS>
      <CLONE>YES</CLONE>
      <CLONE_TARGET>SYSTEM</CLONE_TARGET>
      <CLUSTER_ID>0</CLUSTER_ID>
      <DATASTORE>default</DATASTORE>
      <DATASTORE_ID>1</DATASTORE_ID>
      <DEV_PREFIX>vd</DEV_PREFIX>
      <DISK_ID>0</DISK_ID>
      <DISK_SNAPSHOT_TOTAL_SIZE>0</DISK_SNAPSHOT_TOTAL_SIZE>
      <DRIVER>qcow2</DRIVER>
      <IMAGE>testvm</IMAGE>
      <IMAGE_ID>0</IMAGE_ID>
      <IMAGE_STATE>9</IMAGE_STATE>
      <LN_TARGET>NONE</LN_TARGET>
      <ORIGINAL_SIZE>8192</ORIGINAL_SIZE>
      <READONLY>NO</READONLY>
      <SAVE>NO</SAVE>
      <SIZE>8192</SIZE>
      <SOURCE>/var/lib/one//datastores/1/1ed09a74e6549c26a75a0b2d7cb46d44</SOURCE>
      <TARGET>vda</TARGET>
      <TM_MAD>shared</TM_MAD>
      <TYPE>FILE</TYPE>
    </DISK>
...
    <NIC>
      <AR_ID>0</AR_ID>
      <BRIDGE>br1</BRIDGE>
      <CLUSTER_ID>0</CLUSTER_ID>
      <IP>192.168.10.100</IP>
      <MAC>02:00:c0:a8:0a:64</MAC>
      <NETWORK>private</NETWORK>
      <NETWORK_ID>0</NETWORK_ID>
      <NIC_ID>0</NIC_ID>
      <SECURITY_GROUPS>0</SECURITY_GROUPS>
      <TARGET>one-0-0</TARGET>
      <VN_MAD>dummy</VN_MAD>
    </NIC>
...
  </TEMPLATE>
...
```

**Comment by rvalle** [comment]
As far as I remember network and storage options are defined by cluster. But I think this is a good question for the forum.

**Comment by rvalle** [comment]
Network might be a good element to group by also.

**Comment by marcindulak** [comment]
I've created an ansible branch for the inventory script and provided the link in the top post.

The script allows for reading of connection variables from an ini config file, and has additional inventory groups: DISK_CLUSTER_ID, NIC_CLUSTER_ID, HOSTNAME.
Apparently each NIC can belong to a different CLUSTER_ID and the inventory reflects this now.

I made a choice that ansible_host corresponds to the IPv4 address on the first NIC. I'm not sure we can do anything better than this.

**Comment by rvalle** [comment]
Great! it looks fantastic. 

With regards to the NIC. I noticed that the TEMPLATE will take non standard parameters, and from the XSD point of view, there can be anything inside TEMPLATE. So, it would be possible to setup a parameter that overrides the default behaviour, such as ANSIBLE_DEFAULT_NIC or something similar. You might want to check with the OpenNebula team/forum if that use of the TEMPLATE is OK or not.

Also, notice that pyone is published as a standard package. I noticed that you refer to the github if the module is not present.

I have now started pushing to https://github.com/privazio/ansible/tree/opennebula-dev where I started creating the structure for ansible commands, feel free to contribute there.

**Comment by rvalle** [comment]
@marcindulak are you experimenting XML validation errors when running your inventory generation script?

Have a look at issue #6, also it would be a good idea if @Madko tests it in his environment.

**Comment by Madko** [comment]
Sure I will test that

**Comment by Madko** [comment]
Well, I'm stuck with pyxb exceptions about invalid content :(

**Comment by marcindulak** [comment]
I've made changes to one.py inventory so command line options can be given to select opennebula network id and the nic index within that network id for ansible IP address. This works only when running one.py with python and not with `ansible -i one.py` due to https://github.com/ansible/ansible/issues/20432

**Comment by marcindulak** [comment]
The `one.py` inventory script https://github.com/marcindulak/ansible/tree/one-dynamic-inventory/contrib/inventory is updated to use the generateDS branch - please give a try.

**Comment by Madko** [comment]
I've just tried this script and it fails:
```
Traceback (most recent call last):
  File "./one.py", line 414, in <module>
    main()
  File "./one.py", line 406, in main
    ansible_network_id=args.ansible_network_id,
  File "./one.py", line 343, in get_inventory
    vms[name] = get_host_dict(vm_data)
  File "./one.py", line 287, in get_host_dict
    groups[group]['IP'] = [entry['IP'] for entry in template_data]
  File "./one.py", line 287, in <listcomp>
    groups[group]['IP'] = [entry['IP'] for entry in template_data]
KeyError: 'IP'
```
I guess this is because it suppose IP to be in the VM template ?

**Comment by marcindulak** [comment]
The purpose of the dynamic inventory script `one.py` is to "guess" the IP address that is used by ansible.
It assumes all NIC have IP defined. In your case, does it mean that some of NIC do not have IP address defined?

I've committed a change https://github.com/marcindulak/ansible/commit/7ddefb5e6250574273f84a5e57c46e99692c5e08 that sets undefined IP addresses to None. Basically it does:

```
vmpool = one.vmpool.info(-3, -1, -1, -1)
template_data = vmpool.VM[0].TEMPLATE['NIC']
print([entry['IP'] if 'IP' in entry else None for entry in template_data])
```

Will this work for you?

**Comment by Madko** [comment]
Some of our VM use DHCP so there is no IP in VM definition. And you can also have VM behind vrouter, or on tier private network, so yes I think that VM with no IP, or no useful IP (ie directly reachable from the ansible client) could occur a lot.

I guess this script purpose is to have something simular to the manual inventory.txt. If there is an IP address:
`VM_NAME ansible_host=IP`
if there is no IP address:
`VM_NAME`
In this case we depend on DNS resolution for VM_NAME. If you think people won't have DNS, then the script should just ignore VM without IP.

And maybe I will adapt this inventory script to use a PROXY_CMD attributs in the VM definition so ansible can connect thru a vrouter etc.

Anyway, sorry if I'm not clear, the most important part is: yes VMs with no IP happen. 

Best regards,
Edouard

**Comment by marcindulak** [comment]
These are the lines relevant for outputting `ansible_host` https://github.com/marcindulak/ansible/blob/7ddefb5e6250574273f84a5e57c46e99692c5e08/contrib/inventory/one.py#L377-L383. Currently `ansible_host` will be set to null in the json output of `one.py` for a VM without IP, and ansible seems trying to use the VM name as DNS name instead for such VMs. Does this work for you, in the sense that `one.py` does not fail?

**Comment by Madko** [comment]
yes this would be perfect. I think this is the famous cat vs cattle. If you deal with thousands of VM you don't want your inventory script to stop at the first malformed VM (and you don't care about those VMs).

If I try this version of the script, it doesn't crash anymore, but it seems to exit at the first VM with a network "problem". 
`Incorrect ansible-nic-index or ansible-network-id for VM ID 105`

**Comment by marcindulak** [comment]
With the latest commit https://github.com/marcindulak/ansible/commit/c28c035db29524228bdf2a3ce4383cf9e259b2bf `one.py` should assign `null` as `ansible_host` for such VMs.
`one.py` will still print the errors (to stderr) as above, but won't stop. Can you try it again?

**Comment by Madko** [comment]
with this commit it won't stop but fails with this error:
```
Traceback (most recent call last):
  File "./one.py", line 423, in <module>
    main()
  File "./one.py", line 415, in main
    ansible_network_id=args.ansible_network_id,
  File "./one.py", line 352, in get_inventory
    vms[name] = get_host_dict(vm_data)
  File "./one.py", line 287, in get_host_dict
    template_data = vm_data.TEMPLATE[group]
KeyError: 'NIC'
```

I haven't find yet on which VM it crash.  Still looking

**Comment by Madko** [comment]
Ok I think it's when it gets a VM without any NIC in its definition.

**Comment by marcindulak** [comment]
You can find such VMs with:

```
vmpool = one.vmpool.info(-3, -1, -1, -1)
print([(vm.ID, vm.NAME) for vm in vmpool.VM if 'NIC' not in vm.TEMPLATE])
```

With https://github.com/marcindulak/ansible/commit/83ea2e474f8755b0533895964841a8d382b536a6, such VMs will get inventory values populated with empty lists. Does it work better now?

**Comment by rvalle** [comment]
Perhaps you could group the VMs in your dynamic inventory according to the addressing in use.
You could have a DHCP group, where the VM name is assumed as valid hostname.
An IP group where the VMs had a specified IP, and perhaps IPV6 if they use this type of addressing.
I think you should also group by Virtual NET automatically, that would solve the problem of segments non-accessible from the ansible control node. 

Then you can choose how you write your playbooks and perhaps target only VMs that you know you can actually target.

**Comment by rvalle** [comment]
pyone seems to be a bit more stable now. I think its time to start building the ansible modules.

I have been looking at what is there already. there is a product called "one view", and some symbols starting by one.

I think I rather stick to opennebula_* for naming the modules, just like docker_* or digital_ocean_*

I see other modules use abbreviations, but as the ecosystem grows, I rather pick the clear name.

you might also want to match the naming with the inventory script.

**Comment by marcindulak** [comment]
I've renamed  `one.*` -> `opennebula.*`. Added also an `ansible_host` inventory group that contains all hosts that have ` ansible_host` set to non-null value. Would be good if @Madko can comment on the current functionality of the `opennebula.py` inventory script.

**Comment by rvalle** [comment]
@marcindulak I was reviewing the documentation of Ansible with regards to development and contributing.
I noticed that this is an active area. Inventory scripts are being elevated to Plugins and Plugins should integrate with a configuration system, etc.

I have not reviewed it in detail but my first impression is that this affect us here. di d you noticed it?

**Comment by marcindulak** [comment]
I noticed the inventory plugins, but their structure and usage is not clear to me. 
I've submitted https://github.com/ansible/ansible/pull/38779 - if an inventory plugin is a must and an inventory script no longer accepted ansible will let me know.

**Comment by marcindulak** [comment]
I've received an answer on #ansible-devel irc that inventory scripts are no longer accepted.
I'll need to find time to work on an inventory plugin.

**Comment by howels** [comment]
Is there a plan to produce an inventory plugin?

**Comment by rvalle** [comment]
@howels I would say yes.
On one hand OpenNebula is taking over this project and making part of the official distribution, so, if you are a customer you should let them know you have an interest on it.
I will also needed myself, but I have to finish 3 or 4 ansible modules before that. 

One way or another, there will be one. 

Can you open a separate issue and we can communicate progress there?

**Comment by howels** [comment]
Thanks, opened #27

**Comment by howels** [comment]
hello @rvalle has there been any progress on this?
