### ISSUE TITLE
generateDS branch fails on one.vmpool.info

### ISSUE THREAD

**Issue by marcindulak** [OpenNebula/addon-pyone#12]
I've tried https://github.com/OpenNebula/addon-pyone/commit/5937ed5e28fdf3c2d42ed31ed02ea69e2cdeac4d - `one.hostpool.info` from https://github.com/OpenNebula/addon-pyone/tree/generateDS#usage works but `one.vmpool.info` has errors:

```
pip list
#dicttoxml (1.7.4)
#future (0.16.0)
#generateDS (2.29.11)
#lxml (4.2.0)
#pip (9.0.2)
#setuptools (0.9.8)
#six (1.10.0)
#xmltodict (0.11.0)

PYTHONPATH=~/py27.generateDS/addon-pyone python -c 'import pyone; one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS"); print(one.vmpool.info(-3,-1,-1,-1).toxml())' | xmllint --format -
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/root/py27.generateDS/addon-pyone/pyone/__init__.py", line 82, in _ServerProxy__request
    return self.__response(ret)
  File "/root/py27.generateDS/addon-pyone/pyone/__init__.py", line 97, in __response
    return bindings.parseString(ret)
  File "/root/py27.generateDS/addon-pyone/pyone/bindings/__init__.py", line 1250, in parseString
    rootObj.build(rootNode)
  File "/root/py27.generateDS/addon-pyone/pyone/bindings/supbind.py", line 4216, in build
    self.buildChildren(child, node, nodeName_)
  File "/root/py27.generateDS/addon-pyone/pyone/util.py", line 100, in buildChildren
    super(TemplatedType, self).buildChildren(child_,node,nodeName_,fromsubclass_)
  File "/root/py27.generateDS/addon-pyone/pyone/bindings/supbind.py", line 4223, in buildChildren
    obj_.build(child_)
  File "/root/py27.generateDS/addon-pyone/pyone/bindings/supbind.py", line 4434, in build
    self.buildChildren(child, node, nodeName_)
  File "/root/py27.generateDS/addon-pyone/pyone/util.py", line 99, in buildChildren
    if not build_template_node(self, nodeName_, child_):
  File "/root/py27.generateDS/addon-pyone/pyone/util.py", line 89, in build_template_node
    obj.USER_TEMPLATE = child2dict(child)
  File "/root/py27.generateDS/addon-pyone/pyone/util.py", line 77, in child2dict
    ret[tagName]._root = ret
AttributeError: 'NoneType' object has no attribute '_root'
-:1: parser error : Document is empty
```

and with python 3:
```
PYTHONPATH=~/py34.generateDS/addon-pyone python -c 'import pyone; one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS"); print(one.vmpool.info(-3,-1,-1,-1).toxml())' | xmllint --format -
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/py34.generateDS/addon-pyone/pyone/__init__.py", line 15, in <module>
    from pyone import bindings
  File "/root/py34.generateDS/addon-pyone/pyone/bindings/__init__.py", line 28, in <module>
    import supbind as supermod
ImportError: No module named 'supbind'
-:1: parser error : Document is empty
```

**Comment by rvalle** [comment]
Please note:
```
PYTHONPATH=~/py27.generateDS/addon-pyone python -c 'import pyone; one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS"); print(one.vmpool.info(-3,-1,-1,-1).toxml())' | xmllint --format -
```
the method ```.toxml()``` was provided by PyXB, same as toDOM(). 

I am not sure if that is the problem, thou. I think here is a problem with the content of the USER_TEMPATE of one of the VMs returned. 
But I cannot figure out what. Would be great if you can get the XML sample. You can get it pyone.__init__.py line 97

Python 3 is not ready yet. I have issues related to binary vs str types.

**Comment by marcindulak** [comment]
Attached what is returned by modifying https://github.com/OpenNebula/addon-pyone/blob/b9f207957766023f383c6d103139ff9a5c69202e/pyone/__init__.py#L92-L98

```
        if sucess:
            ret = rawResponse[1]
            if isinstance(ret, string_types):
                # detect xml
                if ret[0] == '<':
                    print(ret.encode('utf-8'))
                    import sys
                    sys.exit(1)
                    return bindings.parseString(ret)
            return ret
```

```
PYTHONPATH=~/py27.generateDS/addon-pyone python -c 'import pyone; one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS"); print(one.vmpool.info(-3,-1,-1,-1))' > issue12.txt
```

[issue12.txt](https://github.com/OpenNebula/addon-pyone/files/1824444/issue12.txt)

Maybe the problem is related to experimenting with characters from other locales. The VM name is `<NAME>testvmæ-1</NAME>`.

**Comment by rvalle** [comment]
Thanks!
I can reproduce the issue. Fails in an USER_TEMPLATE that is empty.  Will create a test case for it.
I have tested that case before... will see why fails here.
We already have some tests with international UFT8 chars, that is supposed to be fixed.

**Comment by rvalle** [comment]
That was a very good catch. 
It fails on empty templates when the XML did not include the name-space only.
Apparently I tested with samples that included the name-space.

... and travis is complaining about your fanny UTF-8 character, apparently the output print is setup to ascii.

**Comment by rvalle** [comment]
I have setup the generateDS output encoding to utf-8, and that made travis happy again (on 2.7)

**Comment by marcindulak** [comment]
With 
https://github.com/OpenNebula/addon-pyone/commit/f2668cf2889af5c425df2aba1899db0a69797811
what is the way to achieve the following as in master?

```
from pyone.util import one2dict
import pyone
one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS" )
vmpool = one.vmpool.info(-3, -1, -1, -1)
print([vm['NAME'] for vm in one2dict(vmpool)['VM_POOL']['VM']])
```

**Comment by rvalle** [comment]
Now dictionaries are automatically used on anyType elements: that is TEMPLATE and USER_TEMPLATE
For the rest you use the generated bindings, that is like the normal member access of any python object. 

so you would do:

```
vmpool = one.vmpool.info(-3, -1, -1, -1)
print([ vm.NAME for vm in vmpool.VM ])
```
You still have the conversion to dictionary, but only inside the templates, for for example

```
vm.TEMPLATE['CPU'] 
```

**Comment by marcindulak** [comment]
It seems like generateDS branch always prints xml to the screen, even with just `vmpool = one.vmpool.info(-3, -1, -1, -1)` - can you verify?

**Comment by rvalle** [comment]
Yes, I noticed in Travis. For some reason doesn't do it inbmy dev environment.

Will look into it.

**Comment by rvalle** [comment]
@marcindulak the XML printing thing is fixed now. You need to make clean all to regenerate the bindings.
