### ISSUE TITLE
generateDS branch: improve tests/integration/test_integration.py

### ISSUE THREAD

**Issue by marcindulak** [OpenNebula/addon-pyone#13]
1. allow for environment variables in https://github.com/OpenNebula/addon-pyone/blob/5937ed5e28fdf3c2d42ed31ed02ea69e2cdeac4d/tests/integration/test_integration.py#L24-L25

2. CentOS7 python 2.7 does not accept ssl context https://bugzilla.redhat.com/show_bug.cgi?id=1490392

```
PYTHONPATH=~/py27.generateDS/addon-pyone python test_integration.py
Traceback (most recent call last):
  File "test_integration.py.orig", line 26, in <module>
    one = pyone.OneServer(testEndpoint, session=testSession, context=ssl._create_unverified_context())
  File "/root/py27.generateDS/addon-pyone/pyone/__init__.py", line 59, in __init__
    xmlrpc.client.ServerProxy.__init__(self, uri, **options)
TypeError: __init__() got an unexpected keyword argument 'context'
```

Certificate checking can be bypassed on CentOS7 python 2.7 with ` PYTHONHTTPSVERIFY=0` https://access.redhat.com/articles/2039753. When ` PYTHONHTTPSVERIFY=0` do not use `context=ssl._create_unverified_context()`.

3. suggest and document running the tests in README.md 

```
PYTHONPATH=~/py27.generateDS/addon-pyone python -m unittest discover -s ~/py27.generateDS/addon-pyone/tests/integration -p 'test_*.py'
```

**Comment by marcindulak** [comment]
`test_integration.py` is still not setup correctly for CentO7, we simply can't use the `context` keyword at all:

```
--- test_integration.py.orig    2018-03-21 22:26:28.601459061 +0000
+++ test_integration.py 2018-03-21 22:23:43.126876228 +0000
@@ -28,11 +28,9 @@
 
 # Disable SSL checks for TEST environment only, and deal with Centos, see issue #13
 if "PYTHONHTTPSVERIFY" in os.environ:
-    testContext = None
+    one = pyone.OneServer(testEndpoint, session=testSession)
 else:
-    testContext = ssl._create_unverified_context()
-
-one = pyone.OneServer(testEndpoint, session=testSession, context= testContext)
+    one = pyone.OneServer(testEndpoint, session=testSession, context=ssl._create_unverified_context())
 
 class IntegrationTests(unittest.TestCase):
 
@@ -44,7 +42,11 @@
 
     def test_auth_error(self):
         with self.assertRaises(pyone.OneAuthenticationException):
-            xone = pyone.OneServer(testEndpoint, session="oneadmin:invalidpass", context=ssl._create_unverified_context())
+            # Disable SSL checks for TEST environment only, and deal with Centos, see issue #13
+            if "PYTHONHTTPSVERIFY" in os.environ:
+                xone = pyone.OneServer(testEndpoint, session="oneadmin:invalidpass")
+            else:
+                xone = pyone.OneServer(testEndpoint, session="oneadmin:invalidpass", context=ssl._create_unverified_context())
             xone.hostpool.info()
 
     def test_market_info(self):
```

Even after this change it looks like the tests do not behave well.
```
 PYTHONHTTPSVERIFY=0 python -m unittest discover --verbose -s . -p 'test_*.py'
test_auth_error (test_integration.IntegrationTests) ... ok
test_empty_dictionary (test_integration.IntegrationTests) ... ok
test_international_characters_issue_006 (test_integration.IntegrationTests) ... ok
test_invalid_method (test_integration.IntegrationTests) ... ok
test_market_info (test_integration.IntegrationTests) ... ok
test_modify_template (test_integration.IntegrationTests) ... ok
test_pool_info (test_integration.IntegrationTests) ... ok
test_retrieve_template_as_DOM_no_longer_working (test_integration.IntegrationTests) ... ok
test_retrieve_template_as_deprecated_dict (test_integration.IntegrationTests) ... ok
test_retrieve_template_as_new_dict (test_integration.IntegrationTests) ... ok
test_template_attribute_vector_parameter (test_integration.IntegrationTests) ... ok
test_vm_info (test_integration.IntegrationTests) ... []
ERROR
test_vm_pool (test_integration.IntegrationTests) ... ok
test_xml_template_parameter (test_integration.IntegrationTests) ... ok

======================================================================
ERROR: test_vm_info (test_integration.IntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/test_integration.py", line 122, in test_vm_info
    labels = vm.USER_TEMPLATE['LABELS']
KeyError: 'LABELS'

----------------------------------------------------------------------
Ran 14 tests in 0.151s

FAILED (errors=1)
```

My understanding is that some of the tests are setting `LABELS` - but apparently this does now work, and only the `test_vm_info` test complains. The tests should be testing the outcome immediately, otherwise we need to carefully order the tests. Does `test_integration.py` set the `LABELS` for you?

Another question - you are using `PYONE_SESSION` and `PYONE_ENDPOINT` - are these variables settled, I would like to use the same variables for the dynamic inventory script https://github.com/OpenNebula/addon-pyone/issues/10?

**Comment by rvalle** [comment]
Can you pull request? I use another distro.
Might be easier

**Comment by rvalle** [comment]
I am happy to settle PYONE session and endpoint

With the config file we should also look into making it fir with whatever conf the ansible module will need, if any. I mean we can expect the conf file to change when we start with the module. 

Personally I don't like leaving clear text passwords on files, I normally use the Vault. 

I am not sure if inventory scripts can use the Vault for configuration thou.

**Comment by marcindulak** [comment]
Normally dynamic inventory scripts store credentials in plain text files https://github.com/ansible/ansible/blob/devel/contrib/inventory/openstack.yml or read credentials from environment variables.

Apparently it is possible to ansible-vault decrypt a config file used by a dynamic inventory when using dynamic inventory plugin ansible/ansible#21164. Examples are here https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/inventory, but I'm not familiar with them.

You could use ansible-vault to export environment variables PYONE_SESSION, PYONE_ENDPOINT saved in a file, like this https://fmarques.org/using-ansible-vault-with-environment-variables/ and call `one.py`.

**Comment by rvalle** [comment]
Yes, the LABELS used to work. But maybe its broken and LABELS were already there. I guess the test should add, check and clean LABELS.

**Comment by rvalle** [comment]
sorry @marcindulak LABELS are created in tests for the HOSTs.
you are right, that test is wrong, requires LABELS to exist beforehand.
I will change the call to a get method with default value, that can handle the case in which there is no labels set.
