### ISSUE TITLE
Add centos7 and other platforms supported by opennebula to travis.yml

### ISSUE THREAD

**Issue by marcindulak** [OpenNebula/addon-pyone#18]
The build/install process is not tested on CentOS7 and other platform listed at http://docs.opennebula.org/5.4/deployment/opennebula_installation/frontend_installation.html

https://github.com/OpenNebula/addon-pyone/issues/16
https://github.com/OpenNebula/addon-pyone/issues/17

**Comment by rvalle** [comment]
Can you pull-request?

**Comment by marcindulak** [comment]
Let me try.

**Comment by rvalle** [comment]
OK! now all tests are passing, that is 39 tests x 12 platforms.

This allowed us to catch 2 new issues: Enums in 3.4 not working, and fixtures failing in some others. 

Thanks!
