### ISSUE TITLE
API to delete VM is successful even when the VM does not exist

### ISSUE THREAD

**Issue by kulkarpo** [OpenNebula/addon-pyone#26]
>>>deletedVM = one.vm.action("terminate", 600) 
>>>#where vm id 600 does not exist
>>>deletedVM
600

the return value is always the vm `identifier` that is passed to the api call instead of success/failure

**Comment by rvalle** [comment]
interesting... we will have to trace it with underlying XMLRPC calls.

What is the expected behavior? have you tried reproducing this issue from the cli?

**Comment by kulkarpo** [comment]
Expected behaviour could be returning a True/False denoting success/failure according to XML-RPC API  defined in Open Nebula docs.
I have not tried the cli. 

Actually this issue is valid for more APIs, couple of them that i tried with -
>>> one.vm.attach(..., ...) # disk attach 
>>> one.vm.detach(..., ...) # detach disk

return value  of such APIs should be boolean indicating Success/Failure of the command, instead these calls just return vm identifier

**Comment by rvalle** [comment]
ok, will look into it when I get a change.
we need to check the cli to understand if this is a pyone issue or not.

**Comment by rvalle** [comment]
@xorel to me this makes sense.
Normally all automation software, such as ansible, etc. Implement commands to take the system to a desired state.
If you see VM deletion operation as: "take my opennebula to the state in which this VM is deleted", then the observed behaviour is perfectly OK.

I am going to go ahead and close this issue.
