### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by maarten-k** [OpenNebula/addon-pyone#5]
My default python version, which is python 3.5, does not cope well with this module  Currently, I am not able to use it because of syntax errors, which are caused by python 2 syntax.  I love to see some forward 
compatibility.

**Comment by rvalle** [comment]
Yes, I think we need to look into this.

Is there any possibility you can send pull-requests?

did you have a look into this?

**Comment by rvalle** [comment]
@maarten-k do you get the tests to pass with the patch applied?

I am trying to test the patched code with python 3.6, but it is complaining about other things also.

I cannot import "bindings", and apparently the xmlrpc library is different in 3.x 

I am going to merge the patch anyway, because it is required for python 3 support, but I think it is not enough, is it?

**Comment by maarten-k** [comment]
`import xmlrpc.client`  works in python 3 but not in python 2. (the client and server are merged into one module).  I do not think there is a clean way to fix this. I see two options

- install the module `future` in python 2 so python 2 recognizes   `import xmlrpc.client`
- create an ugly try...except  setup to load the right module 

I don't know what the best approach is.

**Comment by maarten-k** [comment]
@rvalle I have made some changes in my fork and python 2 and 3 should work, but tests are failing: the order of the dictionaries are changed. Is the order of the dictionaries critical?

**Comment by maarten-k** [comment]
@rvalle  I made a basic Travis (.travis.yml)script for testing under python 2.7 and 3.6.  This makes the testing process for multiple versions a bit easier.  Currently, python 2.7 works nicely, however, python 3.6 still has the dictionary order issue.

**Comment by rvalle** [comment]
Yes, I can see that now.
Let me setup travis. The tests should be easy to fix.

**Comment by maarten-k** [comment]
@rvalle  shall I make a pull request for the latest stuff?

**Comment by rvalle** [comment]
Sure.
I am waiting for admin access in travis, since this repo is now part of OpenNebula, they have to enable it.
Then I will setup the travis-ci also.

**Comment by rvalle** [comment]
We still have to fix the tests... but this PR is merged and now Travis should be working...

**Comment by rvalle** [comment]
I notice that you fixed the tests also...

**Comment by rvalle** [comment]
the integration tests have some trouble sending XML as parameters.
in 2.7 the XML is passed as, what it looks like, an urlencoded string, which seems to be accepted by OpenNebula
in 3.6 the XML is passed as base64, which generates an exception.
the failing test is the test_xml_template_parameter

I am not 100% sure that the 2.7 way of uploading the parameter is correct either. I guess there is a spec somewhere to look at...

**Comment by rvalle** [comment]
@maarten-k thanks for your contribution
I have now bumped a new release that is python 3 compatible.
