### ISSUE TITLE
Error when fetching details of VNET

### ISSUE THREAD

**Issue by mmeroberts** [OpenNebula/addon-pyone#9]
Hi I am trying to get the details of networks using the VNETPOOL and I am getting the following error:

raise pyxb.UnrecognizedContentError(self, self.__automatonConfiguration, value, location)
UnrecognizedContentError: Invalid content IP6 at <unknown>[1:3906] (expect {http://opennebula.org/XMLSchema}GLOBAL_PREFIX or {http://opennebula.org/XMLSchema}IP or {http://opennebula.org/XMLSchema}MAC)

This is on OpenNebula 5.4.5

**Comment by mmeroberts** [comment]
It turns out that the schema for the VNET_POOL was not quite right for my deployment.  I changed it to: include the following for the AR_POOL:
              <xs:element name="AR_POOL">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="AR" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ALLOCATED" type="xs:string" minOccurs="0"/>
                          <xs:element name="AR_ID" type="xs:string"/>
                          <xs:element name="GLOBAL_PREFIX" type="xs:string" minOccurs="0"/>
                          <xs:element name="IP" type="xs:string" minOccurs="0"/>
                          <xs:element name="IP6" type="xs:string" minOccurs="0"/>
                          <xs:element name="MAC" type="xs:string"/>
                          <xs:element name="PARENT_NETWORK_AR_ID" type="xs:string" minOccurs="0"/>
						  <xs:element name="PREFIX_LENGTH" type="xs:integer" minOccurs="0"/>
                          <xs:element name="SIZE" type="xs:integer"/>					  
                          <xs:element name="TYPE" type="xs:string"/>
                          <xs:element name="UNDEFINED" type="xs:string" minOccurs="0"/>
                          <xs:element name="ULA_PREFIX" type="xs:string" minOccurs="0"/>
                          <xs:element name="VN_MAD" type="xs:string"  minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

Not extra elements: IP6, PREFIX_LENGTH and UNDEFINED

**Comment by mmeroberts** [comment]
Sorry I did not mean to close it - I would like to know if this a local issue to my deployment or a general opennebula issue

**Comment by rvalle** [comment]
have a look at #6 
we have found several issues, some todo with OpenNebula not issuing XML that does not validate with the XSD.

We are making a compilation of XML responses that don't follow the XSD, which those we will both create unit tests for pyone and also open an issue with OpenNebula.

If you can provide us with the XML just like we are doing in issue #6 that would be great!

**Comment by rvalle** [comment]
@mmeroberts can you send me the XML that caused this errors?
We will push pull requesting changes to the XSDs soon.

**Comment by mmeroberts** [comment]
@rvalle I am sorry I have not done this.  The XML does not belong to my company so I am not at liberty to share it.  I know this is not ideal.  I am not sure what I can do to help.  I could upload my amended schema files if that would help?  Let me know

**Comment by rvalle** [comment]
I understand. I thought they came from a testing environment.
I am just building a test with many failing samples to XML before pull requesting changes to the XSD.

I can see up there the elements that you found missing of the XSD. Thanks for identifying them.

**Comment by rvalle** [comment]
the release v1.1.0 should fix this problem.
Non-conforming XML will be silently ignored with the new binding Generator.
Still is not ideal, as XML and XSD should match each other.

XML elements that do not correspond to an XSD entry will not be accessible from PyONE. However a bug should be opened at OpenNebula, and once they are added to the XSD the problem should go away.

**Comment by mmeroberts** [comment]
Hi Rafael,
  I am not to happy about this as it may mean not being able to get at that
data.

Martin

**Comment by rvalle** [comment]
Totally agree.
Can you open an issue with OpenNebula?
Perhaps you can report them here: https://github.com/OpenNebula/one/issues/1821
Fixing the XSDs is the right thing to do, before considering workarounds we should at list try to push for it.

Also I think that
